brew 'bat'
brew 'coreutils'
brew 'ctop'
brew 'diff-so-fancy'
brew 'dust'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'git'
brew 'gh'
brew 'gnu-sed'
brew 'gnupg'
brew 'httpie'
brew 'jq'
brew 'maven'
brew 'neovim'
brew 'pinentry-mac'
brew 'ripgrep'
brew 'starship'
brew 'stow'
brew 'tealdeer'
brew 'tree'
brew 'wget'
brew 'yq'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'zsh'

tap 'rs/tap'
brew 'curlie'

cask '1password'
cask 'bitwarden'
cask 'cryptomator'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'iterm2'
cast 'netnewswire'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'

tap 'homebrew/cask-fonts'
cask 'font-cascadia-code-pl' # for the terminal
cask 'font-fira-code' # for everything else
